### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [anuraio/anura-for-google-tag-manager#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "instance_id" when generating the url
var url = 'https://script.anura.io/request.js?instance=' + instance_id;
2) Please mention the regular expression for the parameters to be entered to run the tests. Also please mention the validation for the parameters.
3) We are seeing error "Test assertion failed:gtmOnSuccess has not been called.". Please resolve the issue.

![Screenshot 2020-05-21 at 12 19 12 PM](https://user-images.githubusercontent.com/53495700/82597094-4af42700-9b5d-11ea-85ba-7526709046fd.png)

**Comment by v1n2e7t** [comment]
encodeURI has been added to instance_id
tests have been updated as best as possible for the testing environment

**Comment by v1n2e7t** [comment]
input regex has been added for fields that require specific input
